DATA_TYPES = {
    "INT" : type(int()),
    "INTEGER" : type(int()),
    "TINYINT" : type(int()),
    "SMALLINT" : type(int()),
    "MEDIUMINT" : type(int()),
    "BIGINT" : type(int()),
    "UNSIGNED BIG INT" : type(int()),
    "INT2" : type(int()),
    "INT8" : type(int()),
    "CHARACTER(20)" : type(str()),
    "VARCHAR(255)" : type(str()),
    "VARYING CHARACTER(255)" : type(str()),
    "NCHAR(55)" : type(str()),
    "NATIVE CHARACTER(70)" : type(str()),
    "NVARCHAR(100)" : type(str()),
    "TEXT" : type(str()),
    "CLOB" : type(str()),
    "REAL" : type(float()),
    "DOUBLE" : type(float()),
    "DOUBLE PRECISION" : type(float()),
    "FLOAT" : type(float()),
    "BOOLEAN" : type(int()),
    "DATE" : type(str()),
    "DATETIME" : type(str())
}
